version: "3.8"

services:

  order:
    build: DockerfileTest
    image: esswhye/arvent-order:latest
    environment:
      SPRING_PROFILES_ACTICE: dt
    #TESTING SWAGGER
    #    ports:
    #      - 12142:12142
    networks:
      - arvent_backend
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.hostname==Arvent-2"
    volumes:
      - my-arvent:/app

networks:
  arvent_backend:
    external: true

volumes:
  my-arvent: