server:
  port: 12142
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://128.199.228.72:3306/Eviant?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Singapore
    password: requirepass123
    username: root
    tomcat:
      test-on-borrow: true
      validation-query: select 1
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
  security:
    user:
      name: user
      password: password
  flyway:
    url: jdbc:mysql://128.199.228.72:3306/Eviant?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Singapore
    user: root
    password: requirepass123
    validate-on-migrate: off
    enabled: true
    #baseline-on-migrate: true

##https://stripe.com/ chansengyong@live.com
stripe-properties:
  public-key: pk_test_EBCu2AlRV8SpgOcNtklB0NEw006eFS6SPv
  secret-key: sk_test_fjc9NPcjzjq04Ol81X8aIjjD00jRTfSuMB

feign:
  client:
    config:
      default:
        connectTimeOut: 10000
        readTimeout: 10000
        loggerLevel: basic
  hystrix:
    enabled: true

hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000
logging:
  level:
    org.springframework: ERROR
    com.arvent: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log

management:
  management:
    metris:
      export:
        prometheus:
          enabled:
            true
  endpoints:
    web:
      exposure:
        include: shutdown, health, prometheus
  endpoint:
    shutdown:
      enabled: true

