server:
  port: 12142
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:32769/Eviant?useSSL=false&allowPublicKeyRetrieval=true
    password: password
    username: user
    tomcat:
      test-on-borrow: true
      validation-query: select 1
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    user:
      name: user
      password: password
  flyway:
    url: jdbc:mysql://localhost:32769/Eviant?useSSL=false&allowPublicKeyRetrieval=true
    user: user
    password: password
    validate-on-migrate: true
    enabled: false
    #baseline-on-migrate: true
  cloud:
    consul:
      host: 172.28.1.253
      port: 8500

##https://stripe.com/ chansengyong@live.com
stripe-properties:
  public-key: pk_test_EBCu2AlRV8SpgOcNtklB0NEw006eFS6SPv
  secret-key: sk_test_fjc9NPcjzjq04Ol81X8aIjjD00jRTfSuMB
feign:
  client:
    config:
      default:
        connectTimeOut: 10000
        readTimeout: 10000
        loggerLevel: basic
